################################################################################
#' TEL.submitJobStep
#'
#' Submits a job to the TEL server.
#' 
#' @param submission named list representing a submission.
#' @param fisServer FISServer instance.
#' 
#' @return \code{submission} input submission with additional 'fisJob' element representing a job running on FIS.
#' 
#' @export
#' 
TEL.submitJobStep <- function( submission, fisServer=TEL.getServer(), ...) {
    .precondition.checkArgument(!is.null(submission),'submission', " Must be set and can't be NULL.")
    
    # Submit
    submission$fisJob <- submitJob(fisServer, .buildSubmissionJob(submission$parameters))

    if (!is.null(submission$fisJob)&&!is.null(submission$fisJob$id)) {
        submission$status <- 'Submitted'
    } else {
        submission$status <- 'Failed'
        stop(paste("Failed to submit job.\n  Server returned:", response$status, response$error, "\n ", response$exception, ":", response$message))
    }

    submission
}

################################################################################
#' TEL.prepareSubmissionStep
#'
#' Submits a job to the TEL server.
#' @param executionType Identifies the target software to use to execute this job.
#'        E.g. NONMEM, MONOLIX.
#' @param workingDirectory Directory, normally within the system temporary directory,
#'        into which the model file and any data files are expected to have been
#'        copied, and within which the target software will execute the job.
#' @param modelfile Path-less filename, or absolute path, to the model file to be
#'        executed. Note that relative paths are currently not supported.
#' @param extraInputFileExts (Optional) A vector of file extensions (excluding the
#'        dot) that will be used in identifying additional files, from the same
#'        directory as the model file and having the same base name as the model file,
#'        to be included in the execution. Default is null/empty.
#'        Primarily used by PsN e.g. to provide the .lst file for a PsN execution of
#'        an already-executed NONMEM run.
#' @param extraInputFiles (Optional) A vector of paths, either absolute or relative
#'        (to the model file), to any additional files to be included in the execution.
#'        Used as an alternative, and/or in conjunction with, extraInputFileExts.
#'        Default is null/empty.
#' @param ... (Optional) Additional parameters that should be attached to submission.
#' 
#' @return \code{submission} named list containing information relating to the
#'         submission of the job:
#'         \itemize{
#'           \item{\code{status}}
#'             - The status of the execution of the model file, i.e. 'NEW'.
#'           \item{\code{fisJob}} - FIS Job entity returned on submission.
#'           \item{\code{start}} - Submission time (generated by R, not FIS)
#'           \item{\code{parameters}}
#'             - A list capturing the input parameters for submission.
#'           \item{\code{parameters$modelFile}}
#'             - An absolute path to the model file.
#'           \item{\code{parameters$sourceDirectory}}
#'             - The absolute path to the directory in which the MDL file lives.
#'           \item{\code{parameters$workingDirectory}}
#'             - The location used for the execution of the job, normally within
#'               the system temporary directory.
#'           \item{\code{parameters$extraInputFiles}}
#'             - List of extra input files for a job.
#'           \item{\code{parameters$extraInputFiles}}
#'             - List of extra input files for a job.
#'           \item{\code{parameters$commandParameters}}
#'             - Additional command line parameters for the third party tool.
#'           \item{\code{parameters$executionFile}}
#'             - An absolute path to the model file.
#'             
TEL.prepareSubmissionStep <- function( executionType=NULL, workingDirectory = NULL, modelfile = NULL, extraInputFileExts=NULL, 
                                       extraInputFiles=NULL, addargs=NULL, outputSubFolderName = NULL, fisServer=TEL.getServer(), extraParams = list() ) {
    .precondition.checkArgument(!is.null(executionType),'executionType', " Must be set and can't be NULL.")
    .precondition.checkArgument(!is.null(modelfile), 'modelfile', "Must be set and can't be NULL.")
    .precondition.checkArgument(!is.null(workingDirectory), 'workingDirectory',"Must be set and can't be NULL.")
    if (!TEL.serverRunning(fisServer)) {
        stop("Server(s) is/are not running, unable to submit job. Server health details have been made available in the TEL.serverHealthDetails object.")
    }
    
    absoluteModelFilePath <- normalizePath(modelfile)
    
    if (!file.exists(absoluteModelFilePath)) {
        stop(paste('Illegal Argument: file ', absoluteModelFilePath, ' does not exist.'))
    }
    
    submission <- list()
    submission$start <- date()
    
    # Parent folder of the model file is the source directory
    sourceDirectory <- parent.folder(absoluteModelFilePath)
    
    # Resolve the extraInputFileExts against files in the model file's directory
    # and add these files to the existing vector of extraInputFiles
    for (fileExt in extraInputFileExts) {
        fileName <- paste0(file_path_sans_ext(basename(modelfile)), ".", fileExt)
        filePath <- file.path(sourceDirectory, fileName)
        if ( file.exists(filePath) && !file.info(filePath)$isdir ) {
            extraInputFiles <- c(extraInputFiles, fileName)
        }
    }
    
    submission$status <- 'New'
    
    parameters <- extraParams
    parameters$modelFile <- absoluteModelFilePath
    parameters$sourceDirectory <- sourceDirectory
    parameters$executionType <- executionType
    parameters$workingDirectory <- workingDirectory
    parameters$extraInputFiles <- as.list(extraInputFiles)
    parameters$commandParameters <- addargs
    parameters$importDirectory <- file.path(parameters$sourceDirectory, outputSubFolderName)
    
    submission$parameters <- parameters
    return(submission)
}

################################################################################
#' .buildSubmissionJob
#'
#' Builds a list representing a job to be submitted from parameters list
#'
#' @param parameters named list with the following elements:
#'        \itemize{
#'          \item{\code{executionType}} - Execution type (e.g. NONMEM).
#'          \item{\code{modelFile}} - Path to a model file.
#'          \item{\code{workingDirectory}} - Job working directory.
#'          \item{\code{extraInputFiles}} - List for additional input files for job.
#'          \item{\code{commandParameters}} - Command parameters for Third Party Tool.
#'        }
#'
#' @return \code{job} named list representing FIS' job.
#'
.buildSubmissionJob <- function(parameters) {
    submittedJob <- list()
    submittedJob$executionType <- parameters$executionType
    submittedJob$executionFile <- parameters$modelFile
    submittedJob$workingDirectory <- parameters$workingDirectory
    submittedJob$extraInputFiles <- parameters$extraInputFiles
    submittedJob$commandParameters <- parameters$commandParameters
    return(submittedJob)
}

################################################################################
#' TEL.pollStep
#'
#' Continously polls the TEL server (at roughly 20 second intervals) for a
#' specified execution request jobID, until the TEL server either reports the
#' job as having completed successfully or as having failed.
#' 
#' @param submission Named list containing information relating to the
#'        submission of the execution request. The only items required by
#'        this function are:
#'        \itemize{
#'          \item{\code{fisJob}} - A job returned by FIS during submission.
#'        }
#' @param fisServer FISServer instance.
#' 
#' @return Updated \code{submission} named list augmented with the \code{status}
#'         of the job and final FIS job state
#' @export
#'
TEL.pollStep <- function(submission, fisServer=TEL.getServer(), ...) {
    if(is.null(submission)) {
        stop("Illegal Argument: submission can't be null")
    }
    if(!("fisJob" %in% names(submission)) || is.null(submission$fisJob)) {
        stop("Illegal Argument: submission's fisJob element must be set and can't be NULL. Was the job submitted?")
    }
    
    message(sprintf('Job %s progress:', submission$fisJob$id))
    message("Running [ ", appendLF=FALSE )
    while (submission$fisJob$status != 'COMPLETED' && submission$fisJob$status != 'FAILED' ) {
        message(".", appendLF=FALSE)
        job = getJob(fisServer, jobID = submission$fisJob$id);
        if(is.null(job)) {
            stop(sprintf("Illegal State: job with id %s doesn't exist.",submission$fisJob$id))
        }
        submission$fisJob <- job
        Sys.sleep(fisServer@jobStatusPollingDelay)
    }
    message(" ]")
    submission
}

################################################################################
#' TEL.clearUpStep
#'
#' Clears up Job working directories. 
#' 
#' @param submission Named list containing information relating to the
#'        submission of the execution request. The only items required by
#'        this function are:
#'        \itemize{
#'          \item{\code{fisJob}} - A job returned by FIS during submission.
#'        }
#' @param fisServer FISServer instance.
#' 
#' @return Updated \code{submission} named list.
#' 
#' @export
#'
TEL.clearUpStep <- function(submission, fisServer=TEL.getServer(), ...) {
    workingFolder <- file.path(submission$parameters$workingDirectory)
    if (clearUp==TRUE) {
        unlink(workingFolder, recursive=TRUE)
    }
    submission
}

#' TEL.getNotImportedJobIDs
#'
#' @param fisServer FISServer instance.
#' 
#' Gets the IDs of the jobs that have completed but haven't been imported (assuming clearUp=TRUE)
#
TEL.getNotImportedJobIDs <- function(fisServer=TEL.getServer()) {
	
	jobs <- getJobs(fisServer)
	
	notImported <- list()
	
	for (job in jobs) {
		if (job$status == "COMPLETED" && file.exists(job$workingDirectory)) {
			notImported <- c( notImported, job$id )
		}
	}
	
	notImported
}